### ISSUE TITLE
Declare row-object at top level to support GraphQL

### ISSUE THREAD

**Issue by patrikarvidsson** [rdunk/sanity-plugin-table#1]
Thank you for the great work on this! I want to use it for a project I'm working on right now, but it's based around Sanitys implementation of GraphQL and your plugin generates the following error:

`Error: Encountered anonymous inline object "row" for field/type "rows". To use this field with GraphQL you will need to create a top-level schema type for it. See https://docs.sanity.io/help/schema-lift-anonymous-object-type`

It looks like the `object` with the name `row` in your schema needs to be moved out and be declared at top level instead.

**More information:**
https://docs.sanity.io/help/schema-lift-anonymous-object-type
https://www.sanity.io/docs/datastore/graphql

Would appreciate your help with this!

**Comment by rdunk** [comment]
I guess this would just mean implementing separate parts for each schema type (table and row), which should be straightforward? I'm _slightly_ skeptical about introducing another top-level schema type, especially as 'row' is quite a general type. I haven't used GraphQL before, open to suggestions!

**Comment by patrikarvidsson** [comment]
I think what you say makes sense. I tried tinkering a bit with it but couldn't get this to work myself. I'm still very new to React and Sanity and not sure whether you should declare another top-level schema or not, but it seems to be the recommendation from Sanity when it comes to GraphQL (specific types aside).

I understand if you don't want to change the main plugin though, but would you be willing to create another branch for it here on GitHub?

Edit, they do write this which I guess is related to what you wrote:

> While "lifting"/"hoisting" the type to the top-level scope, it can be helpful to consider whether the type should be altered to make it more reusable in other contexts. If you think the type is only relevant to the specific schema type, consider prefixing it to make it clearer (eg. blogPostSponsor in the above case).

**Comment by rdunk** [comment]
Yep, I think `tableRow` would make the most sense if were to lift the row type. I guess I may still be able to name it 'row' in the table schema which would I assume prevent a breaking change... I'll do my best to look at it shortly.

**Comment by roffelsaurus** [comment]
PR #2 should fix this issue @patrikarvidsson . 

While the PR is being evaluated and potentially merged in you can in the mean time pull down my fork and then copy it in with "cp -R sanity-plugin-table ./your-sanity-folder/plugins/prefixotherthansanity-sanity-plugin-table", and then reference it manually in your sanity.json under plugins: [ "prefixotherthansanity-sanity-plugin-table" ].

**Comment by rdunk** [comment]
Hello, sorry I didn't get round to looking at this. Thanks for submitting a PR, I'll take a look and try and get it merged in before the end of the week.

**Comment by intensr** [comment]
little reminder pushy !

**Comment by dotcollective-oscar** [comment]
+1

**Comment by roffelsaurus** [comment]
I did an off-site fork of this plugin to take over maintenance. I also changed it to be a "bring-your-own" schema input plugin, while being 100% backwards compatible with this plugin: https://github.com/ssfbank/sanity-plugin-byo-table

**Comment by flexchar** [comment]
With utmost respect, @rdunk if you do not have time to maintain/decided to abandon, it would be a good idea to include a note on the front README page. :)

**Comment by amandakievet** [comment]
👋 +1 any movement on this one? I am running into this issue and would love to use this plugin.

**Comment by rdunk** [comment]
Looks like the BYO table plugin has probably superseded this plugin but I've merged these changes in regardless. Thanks once again.
