### ISSUE TITLE
Add Row/Col position

### ISSUE THREAD

**Issue by Danm72** [rdunk/sanity-plugin-table#17]
Hey there - it would be really nice to be able to add a row to the top or bottom, or add a column at a particular point.

At this time if we want to add a new row we need to add it to the bottom and then copy all content to the row below it - which isn't the best.

Same issue for cols.

**Comment by rdunk** [comment]
Agreed, would happily accept a PR for this feature.

**Comment by Danm72** [comment]
@rdunk https://github.com/rdunk/sanity-plugin-table/pull/18

**Comment by rdunk** [comment]
Thanks! Merged and published as `2.3.0`.
