### ISSUE TITLE
Warning about missing required focus() method

### ISSUE THREAD

**Issue by dylanjha** [rdunk/sanity-plugin-table#5]
The input component for type "table" is missing a required ".focus()" method. Please check the implementation of "TableInput" [class TableInput]. Read more at https://docs.sanity.io/help/input-component-missing-required-method 
    in FormBuilderInput (created by Stacked)
    in Stacked (created by EditNode)
    in EditNode (created by BlockEditor)
    in BlockEditor (created by BlockEditorInput)
    in BlockEditorInput (created by SyncWrapper)
    in SyncWrapper (created by withPatches(SyncWrapper))
    in withPatches(SyncWrapper) (created by BlockEditorRoot)
    in BlockEditorRoot (created by FormBuilderInput)
    in FormBuilderInput (created by Field)
    in Field (created by ObjectInput)
    in ObjectInput (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in SanityFormBuilder (created by EditForm)
    in EditForm (created by FormView)
    in FormView (created by DocumentPane)
    in DocumentPane

**Comment by rdunk** [comment]
I think this was fixed in a recent PR.
