### ISSUE TITLE
Does not work: value.rows is undefined

### ISSUE THREAD

**Issue by flexchar** [rdunk/sanity-plugin-table#8]
Whenever I try to add new row/column I keep getting undefined error. I am trying to use inside block editor

**Comment by rdunk** [comment]
I assume this was an incompatibility introduced in a new Sanity studio version. This might be fixed in #12, but I'll leave it open for the time being.

**Comment by schlosser** [comment]
I just installed the latest version, and also get this issue.

```
Error: Cannot read property '0' of undefined
Check your browser's JavaScript console for details.
```

The console then shows this stack trace:

```
Error: Invalid call to useReporter(field-body[_key=="af93d352c45d"]): A component reporting on "field-body[_key=="af93d352c45d"]" is already mounted in the subtree. Make sure that all reporters within the same <Tracker> subtree have unique ids.
    at add (createStore.js:30)
    at createUseReporter.js:42
    at commitHookEffectListMount (react-dom.development.js:19732)
    at commitLifeCycles (react-dom.development.js:19788)
    at commitLayoutEffects (react-dom.development.js:22804)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at commitRootImpl (react-dom.development.js:22542)
    at unstable_runWithPriority (scheduler.development.js:653)
```

**Comment by rdunk** [comment]
@schlosser Are you using this with existing data or new data?

**Comment by rdunk** [comment]
I've just published `v2.1.0` as an attempted fix. If you are migrating data from v1 to v2, please follow the configuration instructions in the readme.

**Comment by schlosser** [comment]
I was just putting a new table in a blog post, starting with an empty table.

**Comment by rdunk** [comment]
Ah I see, block text assigns a value by default. I'm able to replicate this, working on a fix.

**Comment by rdunk** [comment]
Give `v2.2.0` a go. I rewrote the entire plugin in TS. It should work correctly with block content now.

**Comment by ThomasSchuller** [comment]
I get this error after creating a table inside a block editor, closing it and then trying to add another row/column after opening it again. 
`Error: Cannot add property 2, object is not extensible`

However, the plugin works as expected when it is not used with block content. I basically can't edit the table in block content after it is created.

Update:
If I remove a row I can add rows again, but the issue comes back when I try to edit it after.

**Comment by flexchar** [comment]
@ThomasSchuller I had error where whole Sanity editor would crash. But updating every package `sanity upgrade` did seem to help. Maybe will help you too!

**Comment by flexchar** [comment]
By the way, thanks for your work @rdunk! It works great!

To mention, I would really love to use it inside block editor and integrate with other editor features such as make text bold/italic etc. I'm not sure if that's up to you or up to Sanity.

**Comment by rdunk** [comment]
@flexchar Glad to hear it. I think supporting things like richer text as you suggested is a good idea, and would be the next logical step for new features.

@ThomasSchuller Thanks, I'm able to replicate, moved the issue to a separate issue #14.
